name: swed
version: 'git' # just for humans, typically '1.2+git' or '1.3.2'
summary: swed # 79 char long summary
description: |
  Swanky Text Editor.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

base: core18

architectures:
  - build-on: amd64
    run-on: all


parts:

  swed:

    plugin: make

    source: .

    override-build: |
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      cp swed $SNAPCRAFT_PART_INSTALL/bin/swed
    
apps:

  swed:

    command: swed


slots:
  cakes:
    interface: content
    read: 
      - swed
