name: swed
version: 'git' # just for humans, typically '1.2+git' or '1.3.2'
summary: Swanky Text Editor. # 79 char long summary
description: |
  Swanky Text Editor.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

base: core20

parts:

  swed:

    plugin: make

    source: .

    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp swed $SNAPCRAFT_PART_INSTALL/bin/swed

    stage-snaps:
      - gamecake/latest/edge

apps:

  swed:

    command: desktop-launch gamecake -lcmd -- swed

    plugs:
      - home
      - x11
      - opengl
      - alsa
      - pulseaudio
      - network
      - joystick
      - hidraw
      - desktop
      - desktop-legacy
      - wayland
      - unity7

    environment:
      ALSA_CONFIG_PATH: /snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa/alsa.conf

